config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :charges do
  get '/charges', to: redirect('/posts')
  end

  resources :groups do 
    member do 
      post 'ajax'
    end
    resources :tournaments do
      member do 
      post 'jointournament'
    end
        resources :events do
        member do 
        post 'joinevent'
      end

end
    end
  end

   root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  serialize :user_id, Array
  has_many :tournaments
  has_many :events, through: :tournaments
end

# def join()
#   @group = Group.find(params[:id])
#     # @group.join
#     @group.users << current_user
# end
# This is doing nothign right now

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @group = Group.new
  end

  def checkmembership
    if @group.users.exists?(current_user.id)
      @member = true
    else
      @member  = false
    end
  end

  def ajax
    @group = Group.find(params[:id])
    # @group.join
    if @group.users.exists?(current_user.id)
      @group.users.delete(current_user)
    else
      @group.users << current_user
    end
    respond_to do | format |
      format.js
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @tournament = Tournament.new

  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    
    @group = Group.new(group_params)


    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
        format.js
        @group.users << current_user  
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :creator_id, :group_description, :imageurl, user_ids:[])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :group_description %><br>
    <%= f.text_area :group_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
  
     <%= f.label :users %><br>
    <% User.all.each do | user | %>
      <%= check_box_tag "group[user_ids][]", user.id %>
      <%= user.name %><br />
    <% end %>


  <%= f.hidden_field :creator_id, :value => current_user.id %>


  
  <div class="actions hide">
    <%= f.submit %>
  </div>

<% end %>

app/views/groups/_groupcontent.html.erb
<% @group.tournaments.each do | tournament | %>
  <li>
    <%= link_to group_tournament_path(@group, tournament) do %>
      <div>  
        <h3>Tournament: <%= tournament.name %></h3> <br>
          <div class="tournamentpreview">
            <div class="tournamentimage">
              <%= image_tag(tournament.imageurl, :class => "tournament_thumb") %>
            </div>

            <ul class="tournamentul">
              <li>
                <div class="tournamentpreviewdescription">
                  <%= tournament.tournament_description %>
                </div>
              </li>
              <li>
                <div class="tournbox tournamentpreviewscore">
                 Current Round:
                </div>
              </li>
               <li>
                <div class="tournbox tournamentpreviewsprize">
                
                <% stake = tournament.users.count * tournament.stake %>

                 Prize Pool: <%=stake%>
                </div>
                <li>
                <div class="tournbox tournamentpreviewstake">
                 Stake to Enter: <%= tournament.stake %>
                </div>
                </li>
              </li>
              <li>
                <div class="jointournament">
                <%= link_to 'Join Tournament', jointournament_group_tournament_path(@group, tournament), id: "jointournament",  remote: true, method: :post %> 
              
                </div>
                </li>
              </li>

            </ul>
         </div>
      </div>
    <% end %>
  </li>  

  <ul class="eventlist">
    <div>
      <h3><%= tournament.name %> Upcoming Events:</h3>
    </div>

    <% if tournament.events.present? %>
     <% tournament.events.each_with_index do | event, index | %>
        <li> 
          <%= link_to group_tournament_event_path(@group, tournament, event) do %>
            <div>  
                Round <%= index + 1 %>: <%= event.name %><br>
                <%= image_tag(event.imageurl, :class => "tournament_thumb") %>
              </div>
          <% end %>
        </li>
      <% end %> 

    <% else %>
        There are no events for this tournament yet
        <% end %>
  </ul>

    </li>
  <% end %>
</ul>

app/views/groups/_groupusers.html.erb
<div class="membersheader">Members</div>
        <ul>
          <% @group.users.each do | user | %>
            <li>
              <% profileimg = user.profile_image_url %> 
              <%= image_tag(profileimg, :alt => "rss feed", :class => "profile_thumb") %>

              </li>
          <% end %>
        </ul>

app/views/groups/_tournamentlist.html.erb
 <% @group.tournaments.each do | tournament | %>
      
      <%= link_to group_tournament_path(@group, tournament) , id:"show", remote: true, method: :get do %>
        <div>  
          <div class="tournamentpreview">
            

            <ul class="tournamentul">
              <li>
                <h3>Tournament: <%= tournament.name %></h3>
                <div class="tournamentimage">
                  <%= image_tag(tournament.imageurl, :class => "tournament_thumb") %>
                  </div>
                <div class="tournamentpreviewdescription">
                  <%= tournament.tournament_description %>
                </div>
              </li>
              <li>
                <div class="sidebarwrap">
                  <div class="tournamentpreviewscore">
                   Tournament Status:
                  </div>
              
                  <div class="tournamentpreviewsprize"> 
                  <% stake = tournament.users.count * tournament.stake %>
                   Prize Pool: <%=stake%>
                  </div>
                 
                  <div class="tournamentpreviewstake">
                   Stake to Enter: <%= tournament.stake %>
                  </div>
                </div>
                
              </li>
              <li>
                <div class="jointournament">
                <%= button_to 'Join Tournament', jointournament_group_tournament_path(@group, tournament), :class =>"btn btn-primary btn-lg", id: "jointournament", method: :post %> 
              
                </div>
              </li>
            </ul>
            
          </div>
        </div>
     
      <% end %>
    <% end %>

app/views/groups/ajax.js.erb
console.log("ajaxfired");

<% if @group.users.exists?(current_user.id) %>
      
    console.log("leaving");
   $('.joingroup').html("<%= escape_javascript(button_to 'Leave group', ajax_group_path, :class =>"btn btn-primary btn-lg", id: "ajax",  remote: true, method: :post ) %>") 
   console.log("joining");

   $('.group_members_top').html("<%= escape_javascript(render partial:'groupusers') %>")

   

    <% else %>
   $('.group_members_top').html("<%= escape_javascript(render partial:'groupusers') %>")
    console.log("leaving");

   $('.joingroup').html("<%= escape_javascript(button_to 'Join group', ajax_group_path, :class =>"btn btn-primary btn-lg", id: "ajax",  remote: true, method: :post )  %>") 

     <%  end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<div class="top">
  <div class="toptext">
    <div class="textwrap">
    <p>Dine With Friends - Eat, Drink, Win.</p>
   
  <div class="createnew">
  <%= link_to "Create New Group", new_group_path, :class => "createnew", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %>
  </div>

 

    <%= form_for(@group) do |f| %>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content" style='color:black;'>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Create Group</h4>
          </div>

          <div class="modal-body">
            <%= render 'form' %>
          </div>
          
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Create", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>




  <p>..Or join an existing group.</p>

   </div>

  </div>

   </div>


<div class="mid1">
<div class="mid1text">
  <p>Dine With Friends is a new kind of social dining experiance.  Create a tournament with a stake and invite your friends, family or strangers even strangers to compete for the 'pot'.
  Meet new people, win cash and determine Once and for All who is the Host with Most.    </p>

 </div>



<div class="groupshome">


  <h1>Latest Groups</h1>

    <div class="grouplist">
    <ul>

      <% @groups.each do |group| %>
          <li>

            <%= image_tag(group.imageurl, :alt => "rss feed", :class => "group_thumb") %>
            <!-- <td><%= group.imageurl %></td> -->
            <h3><%= group.name %></td>
            <!-- <td><%= group.creator_id %></td> -->
            <p><%= group.group_description %></p>
            
            <%= link_to 'Show', group %>
            <%= link_to 'Edit', edit_group_path(group) %>
            <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        <% end %>
      
    </ul>
  </div>

</div>

<div class ="contentwrap">



  

</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label :group_description %><br>
    <%= f.text_area :group_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>

   <%= f.label :users %><br>
    <% User.all.each do | user | %>
      <%= check_box_tag "group[user_ids][]", user.id %>
      <%= user.name %><br />
    <% end %>




  <div class="field">
    <%= f.label "Members(arrayofuids)" %><br>
    <%= f.text_field :user_id %>
  </div>

  <%= f.hidden_field :creator_id, :value => current_user.id %>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>





<%= link_to 'Back', groups_path %>

app/views/groups/new.js.erb
alert("create button clicked")

app/views/groups/show.html.erb
<style media="screen">
  
  .image_show_top{ background-image: url("/assets/<%= @group.imageurl %>"); }

</style>

<div class="image_show_top">

  <div class="imagegreyer">
    
    <div class="buttonsbox">

      <div class="buttonslider">
      <%= image_tag("arrow.png", size:"25", :alt => "rss feed", :class => "arrow") %>

      </div>
    <div class="buttondiv">

      <div class="joingroup">
      <% if @group.users.exists?(current_user.id) %>
         <%= button_to 'Leave group', ajax_group_path, :class =>"btn btn-primary btn-lg", id: "ajax",  remote: true, method: :post %>
        <% else %>
          <%= button_to 'Join group', ajax_group_path, :class =>"btn btn-primary btn-lg", id: "ajax",  remote: true, method: :post %>    
          <% end > %>
      </div>

      <!-- this is the new tournament button -->

      <div class="createnewtourn">

       <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#tourncreatemodal">New Tournament</button>
        </div>

      <%= form_for [@group, @tournament] do |f| %>
        <div class="modal fade" id="tourncreatemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content" style='color:black;'>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Create Tournament</h4>
              </div>

              <div class="modal-body">
                <%= render '/tournaments/form' %>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= submit_tag "Create", class: "btn btn-primary" %>
              </div>
            </div>
         </div>
       </div>
      <% end %>


      <!-- This is the edit button -->

      <div class="editgroup">

       <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Edit Group</button>
        </div>

        <%= form_for(@group) do |f| %>
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content" style='color:black;'>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit Group</h4>
              </div>

              <div class="modal-body">
                <%= render 'form' %>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= submit_tag "Update", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <!-- button box close -->
        </div>

     </div>

    <div class="image_show_top_text">
      <p>
        <strong>Name:</strong>
        <%= @group.name %>
      </p>
      <p><%= @group.group_description %></p>
      
      </div>

      <div class="tournamentsbar">
        <div class="group_members_top"> 
        <%= render 'groupusers' %>
        </div>
      </div>
    </div>

</div>


  <div class="container groupcontent">
      <div class="row">          

        <div class="groupcol2 col-md-10">
          
          <div class='content'>
          <br><br><br><br>
          <br>Please select a tournament from the left hand column.
          </div>

        </div>

        <div class="col-md-2">
             
          <div class="groupscol1">   
          <%= render 'tournamentlist' %> 
          </div>
        
        </div>

      </div>
    </div>
</div>

app/views/groups/show.js.erb
alert("post create clicked")