config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :charges do
  get '/charges', to: redirect('/posts')
  end

  resources :groups do 
    member do 
      post 'ajax'
    end
    resources :tournaments do
      member do 
      post 'jointournament'
    end
        resources :events do
        member do 
        post 'joinevent'
      end

end
    end
  end

   root 'groups#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_and_belongs_to_many :users
  serialize :user_id, Array
  belongs_to :group
  has_many :events
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  def jointournament
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params[:id])

    # @group.join
    if @tournament.users.exists?(current_user.id)
      @tournament.users.delete(current_user)
    else
      @tournament.users << current_user
    end
    respond_to do | format |
      format.js
    end

  end

  # GET /tournaments
  # GET /tournaments.json
  def index
    @group = Group.find(params['group_id'])
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @group = Group.find(params['group_id'])
    @event = Event.new
    @tournament = Tournament.find(params[:id])
    respond_to do | format |
      format.js
      format.html
    end
    session[:group] = @group.id
    session[:tournament] = @tournament.id
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
    @group = Group.find(params['group_id'])
  end

  # GET /tournaments/1/edit
  def edit
        @group = Group.find(params['group_id'])

  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)
    @group = Group.find(params['group_id'])

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to group_tournament_path(@group, @tournament), notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
        @tournament.users << current_user
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1 
  # PATCH/PUT /tournaments/1.json
  def update
    @group = Group.find(params['group_id'])
    respond_to do |format|  
      if @tournament.update(tournament_params)
        format.html { redirect_to group_tournament_path(@group, @tournament), notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :creator_id, :event_description, :imageurl, :start_date, :end_date, :group_id, :stake, user_id:[])
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_eventsshow.html.erb
<div class="eventviewer">
  <h3>Events</h3>
  <ul>
    <% if @tournament.events.present? %>
    <% @tournament.events.each do | event | %>
     <%= link_to group_tournament_event_path(@group, @tournament, event) do %>
      <li>
        <div class="eventhead">
        <%= event.name %> 
        </div>
        <div class="eventbigimg">
        <% eventimg = event.imageurl %> 
        <%= image_tag(eventimg, :alt => "rss feed", :class => "event_big") %>
        </div>
        
        <div class="eventdescription">
        <%= event.event_description %> 
        </div>

        

        

        </li>
      <% end %>
    <% end %>
    <% else %><br><br><br>
    <h2>No events yet for this tournament.</h2>
    <% end %>
  </ul>
</div>  

app/views/tournaments/_form.html.erb
<%= form_for [@group, @tournament] do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :tournament_description %><br>
    <%= f.text_area :tournament_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
  
   <%= f.label :users %><br>
    <% User.all.each do | user | %>
      <%= check_box_tag "tournament[user_ids][]", user.id %>
      <%= user.name %><br />
    <% end %>



  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
 
   <div class="field">
    <%= f.label :stake %><br>
    <%= f.number_field :stake %>
  </div>
  
    <%= f.hidden_field :creator_id, :value => current_user.id %>
    <%= f.hidden_field :group_id, :value => @group.id %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/_tournamentsidebar.html.erb
<div class="tournamentsidebartop">

  
  <p>
    <strong>Group:</strong>
    <%= link_to(@group.name, group_path(@group)) %>
  </p>
  <h3>∟<%= link_to(@tournament.name, group_tournament_path(@group, @tournament)) %> Tournament</h3>
  
  <% if @tournament.users.where(:id => current_user.id).blank? %>
    <div class="stakes">
    Rounds: <%= @tournament.events.count %><br>
    <% stake = @tournament.users.count * @tournament.stake %>
    Prize Pool: £<%=stake%>
    <%= render "./charges/newcharge" %>
    
    </div> 
  <% else %>
  <%= "You have paid the Stake and are enrolled in this tournament" %>
  <% end %>

  

</div>



<div class="title">
  Events
</div>
<ul class="othereventlist">

 <% @tournament.events.each_with_index do | event, index | %>
    <li> 
      
      <%= link_to group_tournament_event_path(@group, @tournament, event) do %>
      <div>  
          Round <%= index + 1 %>: <%= event.name %><br>
          <%= image_tag(event.imageurl, :class => "event_thumb") %>
        </div>



      <% end %>
    </li>
  <% end %> 

  </ul>

app/views/tournaments/_tournamentusers.html.erb
  <div class="slider">
        <ul>
          <% @tournament.users.each do | user | %>
            <li>
              <% profileimg = user.profile_image_url %> 
              <%= image_tag(profileimg, :alt => "rss feed", :class => "profile_thumb") %>

              </li>
          <% end %>
        </ul>
        </div>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', group_tournament_path(@group, @tournament) %> |
<%= link_to 'Back', group_tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th>Tournament description</th>
      <th>Imageurl</th>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>

      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.creator_id %></td>
        <td><%= tournament.tournament_description %></td>
        <td><%= tournament.imageurl %></td>
        <td><%= tournament.user_id %></td>
        <td><%= tournament.start_date %></td>
        <td><%= tournament.end_date %></td>
        <td><%= tournament.group_id %></td>
        <td><%= link_to 'Show', group_tournament_path(@group, tournament) %></td>
        <td><%= link_to 'Edit', edit_group_tournament_path(@group, tournament) %></td>
        <td><%= link_to 'Destroy', group_tournament_path(@group, tournament), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_group_tournament_path %>

app/views/tournaments/jointournament.js.erb
<% if @tournament.users.exists?(current_user.id) %>
  
   $('.jointournament').html("<%= escape_javascript(button_to 'Leave Tournament', jointournament_group_tournament_path, :class =>"btn btn-primary btn-lg", id: "jointournament",  remote: true, method: :post ) %>") 
   $('.group_members_top').html("<%= escape_javascript(render partial:'tournamentusers') %>")
   console.log("memberalready");
    <% else %>
  
   $('.jointournament').html("<%= escape_javascript(button_to 'Join Tournament', jointournament_group_tournament_path, :class =>"btn btn-primary btn-lg", id: "jointournament",  remote: true, method: :post ) %>") 
   $('.group_members_top').html("<%= escape_javascript(render partial:'tournamentusers') %>")
   console.log("memberalready");
     <%  end %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= form_for [@group, @tournament] do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tournament_description %><br>
    <%= f.text_area :tournament_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_area :user_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
 
   <div class="field">
    <%= f.label :stake %><br>
    <%= f.number_field :stake %>
  </div>
    <%= f.hidden_field :creator_id, :value => current_user.id %>
    <%= f.hidden_field :group_id, :value => @group.id %>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', group_tournaments_path %>

app/views/tournaments/show.html.erb
<style media="screen">
  
  .image_show_top{ background-image: url("/assets/<%= @tournament.imageurl %>"); }

</style>

<div class="image_show_top">
  <div class="imagegreyer">

    <div class="buttonsbox">
    <div class="buttonslider">
      <%= image_tag("arrow.png", size:"25", :alt => "rss feed", :class => "arrow") %>

      </div>
      <div class="buttondiv">

      <div class="jointournament">
      <% if @tournament.users.exists?(current_user.id) %>
         <%= button_to 'Leave Tournament', jointournament_group_tournament_path, :class =>"btn btn-primary btn-lg", id: "jointournament",  remote: true, method: :post %>
        <% else %>
          <%= button_to 'Join Tournament', jointournament_group_tournament_path, :class =>"btn btn-primary btn-lg", id: "jointournament",  remote: true, method: :post %>    
          <% end > %>
      </div>

      <div class="createnewevent">

       <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#eventcreatemodal">New Event</button>
        </div>

        <%= form_for [@group, @tournament, @event] do |f| %>
          <div class="modal fade" id="eventcreatemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content" style='color:black;'>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Create Event</h4>
              </div>

              <div class="modal-body">
                <%= render '/events/form' %>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= submit_tag "Create", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>

      </div>

  </div>

    <div class="image_show_top_text">
      <p>
        <strong>Name:</strong>
        <%= @tournament.name %>

      </p>
      <p><%= @tournament.tournament_description %></p>
      
      </div>

     

  </div>
</div>


</div>

  
  
<div class="container groupcontent">
  <div class="content">

  <p id="notice"><%= notice %></p>

      <!-- <div class="row">           -->

        <div class="groupcol2 col-md-10">

        <div class="group_members_top">
        Tournament Members
          <div class="membersheader">
            <%= render 'tournamentusers' %>
          </div>
        </div>

                  
                 <!-- col1 -->

          <p>
            <strong>Tournament Name:</strong>
            <%= @tournament.name %>
          </p>
          
           <div class="tournamentpreviewsprize">
                        <% stake = @tournament.users.count * @tournament.stake %>

                         Prize Pool: £<%=stake%>
                        </div>

          <p>
            <strong>Group:</strong>
            
            <% group = Group.find(@tournament.group_id).name %> 
            <%= group %>
          </p>
            

          <p>
            <strong>Creator:</strong>
            <% creator = User.find(@tournament.creator_id).name %> 
            <%= creator %>
          </p>

          <p>
            <strong>Tournament description:</strong>
            <%= @tournament.tournament_description %>
          </p>

         <!--  <p>
            <strong>User:</strong>
            <%= @tournament.user_id %>
          </p> -->

          <!-- <p>
            <strong>Start date:</strong>
            <%= @tournament.start_date %>
          </p>

          <p>
            <strong>End date:</strong>
            <%= @tournament.end_date %>
          </p>
         -->
          


          <li> <%= link_to('Edit', edit_group_tournament_path(@group, @tournament)) %> </li>
            <li> <%= link_to('Delete', group_tournament_path(@group, @tournament), method: :delete) %></li>

          </div>

       

        <div class="col-md-2">
             
          <div class="groupscol1">   
          <%= render 'tournamentsidebar' %> 
          </div>
        
        </div>
       <!-- </div> -->
      </div>
    </div>

app/views/tournaments/show.js.erb
$('.content').html("<%= escape_javascript(render partial:'eventsshow') %>")