config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :charges do
  get '/charges', to: redirect('/posts')
  end

  resources :groups do 
    member do 
      post 'ajax'
    end
    resources :tournaments do
      member do 
      post 'jointournament'
    end
        resources :events do
        member do 
        post 'joinevent'
      end

end
    end
  end

   root 'groups#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  geocoded_by :location
  after_validation :geocode
  serialize :user_id, Array
  belongs_to :tournament
  has_and_belongs_to_many :users
  has_one :group, through: :tournaments  
  scope :latestevent, -> { order 'start_date ASC' }
  ratyrate_rateable "Rating"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  

  def joinevent
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])
    @event = Event.find(params[:id])


    # @group.join
    if @event.users.exists?(current_user.id)
      @event.users.delete(current_user)
    else
      @event.users << current_user
      @tournament.users << current_user
    end
    respond_to do | format |
      format.js
    end
  end
    
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])
    respond_to do | format |
      format.js
      format.html
    end
    @ratings = @event.rates("Rating")
  end

  # GET /events/new
  def new
    @event = Event.new
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])

  end

  # GET /events/1/edit
  def edit
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      @group = Group.find(params['group_id'])
      @tournament = Tournament.find(params['tournament_id'])
      if @event.save
        format.html { redirect_to group_tournament_event_path(@group, @tournament, @event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
        @event.users << current_user

      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @group = Group.find(params['group_id'])
    @tournament = Tournament.find(params['tournament_id'])
    respond_to do |format|
      if @event.update(event_params) 
        format.html { redirect_to group_tournament_event_path(@group, @tournament, @event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :host_id, :event_description, :imageurl, :start_date, :end_date, :group_id, :tournament_id, :location, :outcome, user_id:[],)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventinfo.html.erb
<% @ratings = @event.rates("Rating") %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span9">
    <!-- Column 1 - Event header - Title -->
    <h3>Event:
      <%= @event.name %>
      <div class="inlinejoinbutton">
        <div class="joinevent">
          <% if @event.users.exists?(current_user.id) %>
             <%= button_to 'Leave Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post %>
            <% else %>
              <%= button_to 'Join Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post %>    
              <% end > %>
        </div>
      </div>
    </h3>

    <div class="row">
      <!-- Column 1 - Event header - col1 -Hose image -->
      <div class="col-md-2">      
        <% profileimg = User.find(@event.host_id).profile_image_url %> 
        <%= image_tag(profileimg, :alt => "rss feed", :class => "circularprofilepic") %><br>
        <strong>Host:</strong>
        <% host = User.find(@event.host_id).name %> 
        <%= host %>
       </div>
      <!-- Column 1 - Event header- col 2 Event info -->
      <div class="col-md-4">  
        <div class="infowrap">
          <strong>Status:</strong>
          <% if @event.start_date.present? %>
            <% if @event.start_date.past? %>
              <%= 'Event has finished' %>
              <% else %>
              <%= 'Event is coming up' %>
              <% end %>
            <% else %>
              <%= 'Event has not date' %>
            <% end %>

          <strong>Date:</strong>
          <%= @event.start_date.to_date %>
          
          <div class="voteinfo">
            <% users = @event.users.count %>
            <% ratings = @ratings.count %>
            <% if (users == ratings) && (users > 0) %>
              All votes are in!
              <% @event.outcome = 1 %>
              <% @event.save %>
            <% else %>
            <strong>Voting:</strong>
            <%= ratings %> / <%= users %>
            guests have voted.  
            <% end %>
          </div>
        </div>
      </div>  
      <!-- Column 1 - Event header - col3 - Voting -->
      <div class="col-md-2">

        <% @ratings.each do | rating | %>
          <% if current_user.id == rating.rater_id %>
          <% @rated = 1 %>
          <% @ratedevent = rating %>
          <% else %>
          <% end %>
        <% end %>
        
        <% if @rated != 1 %>
         Rating:
        <div class="staravg1">
         <%= rating_for @event, "Rating", stars:10, enable_half: true, disable_after_rate: true  %>
        </div>

        <% else %>
        You rated this event:
        <div class="star1">
         <%= (@ratedevent.stars).round(1) %>
        </div>
        <% end %>


      </div>

    </div>
  </div>
</div>

<div class="group_members_top">
  Guests
  <div class="membersheader">
    <%= render 'eventusers' %>
  </div>
</div>

<div class="infoheader">
  Event Information
  </div>

<div class="eventinfo">

  <div class="eventdescription">
    <p>
      <%= @event.event_description %>
    </p>
  
    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>
  
    <!-- <p>
      <strong>Outcome:</strong>
      <%= @event.outcome %>
    </p> -->

    <div class="eventactive">
      <% ratingscount = @event.rates("Rating").count %>
      <% users = @event.users.count %>

      <% if ratingscount == users %>
      Event complete! All users have voted
       <% @event.outcome = 1 %>
       <% @event.save %>

      <% else %>
      Waiting for guests to finish voting
      <% end %>
    </div>

    
    <% @ratings.each do | rating | %>

    <% rater = User.find(rating.rater_id) %>
    <%= rater.name %>
    <%= (rating.stars).round(1) %>
    <% end %>
    
    <br>
    <% @ratings.each do | rating | %>
      <% if current_user.id == rating.rater_id %>
        Your rating is: <%= (rating.stars).round(1) %>
        <% else %>
      <% end %>
    <% end %>


    

    <td><%= link_to 'Edit', edit_group_tournament_event_path(@group, @tournament, @event) %>
    </td>

    <td><%= link_to 'Destroy', group_tournament_event_path(@group, @tournament, @event), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>

  </div>

  <div class="mapheader">
    Map
  </div>
  

  <div id="map" style='width: 100%; height: 400px;'></div>
     
  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers([
        {
          "lat": <%= @event.latitude %>,
          "lng": <%= @event.longitude %>,
          
          "infowindow": "hello!"
        }
      ]);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>

</div>

app/views/events/_eventusers.html.erb
  <div class="slider">

        <ul>
          <% @event.users.each do | user | %>
            <li>
              <% profileimg = user.profile_image_url %> 
              <%= image_tag(profileimg, :alt => "rss feed", :class => "profile_thumb") %>

              </li>
          <% end %>
        </ul>
        </div>

app/views/events/_form.html.erb
<%= form_for [@group, @tournament, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host_id %><br>
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br>
    <%= f.text_area :event_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
 
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
 

  <%= f.hidden_field :tournament_id, :value => @tournament.id %>
  <%= f.hidden_field :group_id, :value => @group.id %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div class="actions hide">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_otherevents.html.erb
<div class="eventsidebartop">
  <!-- <p>
    <strong>Group:</strong>
    <%= link_to(@group.name, group_path(@group)) %>
  </p> -->
  <h3><%= link_to(@tournament.name, group_tournament_path(@group, @tournament)) %> Tournament
  </h3>
  

  <% if @tournament.users.where(:id => current_user.id).blank? %>
    <div class="stakes">
    <p>
    Rounds: <%= @tournament.events.count %></p>
    <p><% stake = @tournament.users.count * @tournament.stake %>
    Prize Pool: £<%=stake%></p>
    <%= render "./charges/newcharge" %>
    
    </div> 
  <% else %>
    <div class="stakes">
      <p>
      Rounds: <%= @tournament.events.count %></p>
      <p><% stake = @tournament.users.count * @tournament.stake %>
      Prize Pool: £<%=stake%></p><br>
      Current Leader:<br>

      <% nextevent = @tournament.events.where('start_date >= ?', Date.today).order(start_date: :desc) %>
      Next Event: <%= nextevent.first.name %>
      <br>

      <%= "You have paid the Stake and are enrolled in this tournament" %>
     </div>
  <% end %>

</div>



<div class="title">
  Events
</div>

<!-- Event Sidebare UL -->
<ul class="othereventlist">

 <% @tournament.events.latestevent.each_with_index do | event, index | %>
    <li> 
      <!-- Linked LIs with title and image of event -->
      <%= link_to group_tournament_event_path(@group, @tournament, event), method: :get  do %>
      <div>
        <div id="eventtitle"class="eventlititle">  
          Round <%= index + 1 %>: <%= event.name %>
         </div>
          <%= image_tag(event.imageurl, :class => "event_thumb") %>
        </div>

      <% end %>
    </li>
  <% end %> 

  </ul>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<td><%= link_to 'Show', group_tournament_event_path(@group, @tournament, @event) %></td> |
<%= link_to 'Back', group_tournament_events_path %>

app/views/events/eventrates.html.erb
<% users = @event.users.count %>
              <% ratings = @ratings.count %>
              <% if users == ratings %>
                All votes are in!
                <% @event.outcome = 1 %>
                <% @event.save %>
              <% else %>
              <strong>Voting:</strong>
              <%= ratings %> / <%= users %>
              guests have voted.  
              <% end %>

              

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Host</th>
      <th>Event description</th>
      <th>Imageurl</th>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Group</th>
      <th>Tournament</th>
      <th>Location</th>
      <th>Outcome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.host_id %></td>
        <td><%= event.event_description %></td>
        <td><%= event.imageurl %></td>
        <td><%= event.user_id %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.group_id %></td>
        <td><%= event.tournament_id %></td>
        <td><%= event.location %></td>
        <td><%= event.outcome %></td>
        <td><%= link_to 'Show', group_tournament_event_path(@group, @tournament, event) %></td>
        <td><%= link_to 'Edit', edit_group_tournament_event_path(@group, @tournament, event) %></td>
        <td><%= link_to 'Destroy', group_tournament_event_path(@group, @tournament, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Event', new_group_tournament_event_path %>

app/views/events/joinevent.js.erb
<% if @event.users.exists?(current_user.id) %>
  
   $('.joinevent').html("<%= escape_javascript(button_to 'Leave Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post ) %>") 
   $('.membersheader').html("<%= escape_javascript(render partial:'eventusers') %>")
   console.log("memberalready");
    <% else %>
  
   $('.joinevent').html("<%= escape_javascript(button_to 'Join Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post ) %>") 
   $('.membersheader').html("<%= escape_javascript(render partial:'eventusers') %>")
   console.log("memberalready");
     <%  end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for [@group, @tournament, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host_id %><br>
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br>
    <%= f.text_area :event_description %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_area :user_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  
  
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>


  <%= f.hidden_field :tournament_id, :value => @tournament.id %>
  <%= f.hidden_field :group_id, :value => @group.id %>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', group_tournament_events_path %>

app/views/events/rateevent.js.erb
$('.staravg1').click(function() {
    $(".voteinfo").html("<%= escape_javascript(render partial:'eventrates') %>" )
  
});

console.log("rateevent.js loading important"):

app/views/events/show.html.erb
<style media="screen">
  
  .image_show_top{ background-image: url("/assets/<%= @event.imageurl %>"); }

</style>

<div class="image_show_top">
    <div class="imagegreyer">

    <div class="buttonsbox">
    <div class="buttonslider">
    <%= image_tag("arrow.png", size:"25", :alt => "rss feed", :class => "arrow") %>

    </div>
    <div class="buttondiv">

      <div class="joinevent">
        <% if @event.users.exists?(current_user.id) %>
           <%= button_to 'Leave Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post %>
          <% else %>
            <%= button_to 'Join Event', joinevent_group_tournament_event_path, :class =>"btn btn-primary btn-lg", id: "joinevent",  remote: true, method: :post %>    
            <% end > %>
      </div>

      </div>
    </div>  

    <div class="image_show_top_text">
      <p>
        <strong>Name:</strong>
        <%= @event.name %>

      </p>
      <p><%= @event.event_description %></p>
     
      </div>

    </div>

</div>


<div class="container eventcontent">
    <div class="row">

     <div class="col-md-10">          
          <div class='content'>
            <%= render 'eventinfo' %> 
            
          </div>
        </div>

      <div class="col-md-2">
           
        <div class="eventscol1">   
        <%= render 'otherevents' %> 
        </div>
      </div>

      
    </div>
</div>